name: freela_fabiano
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  android_intent_plus: ^5.1.0
  animated_splash_screen: ^1.3.0
  device_apps: ^2.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  get: ^4.6.6
  lottie: ^3.1.2
  open_file: ^3.5.8
  package_info_plus: ^8.0.3
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/game/SpaceShooter.apk
    - assets/game/jogo2.apk
    


  fonts:
    - family: KanitBold
      fonts:
        - asset: assets/fonts/Kanit-Bold.ttf

    - family: LEMONMILK
      fonts:
        - asset: assets/fonts/LEMONMILK-Regular.otf

    - family: LemonMilk-bold
      fonts:
        - asset: assets/fonts/LEMONMILK-Bold.otf
    
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed.ttf

  
